[versions]
agp = "8.2.0"
android-test = "1.5.0"
android-test-runner = "1.5.2"
androidx-activity = "1.8.1"
androidx-core = "1.12.0"
androidx-fragment = "1.6.2"
androidx-navigation = "2.7.5"
androidx-test-ext-junit = "1.1.5"
astronomy = "bd2db6a3805ac8a7c559b6b2276e16c1e1793d1f" # is equal to v2.1.17
browser = "1.7.0"
compose = "1.6.0-beta02"
compose-accompanist = "0.32.0"
compose-compiler = "1.5.6" # https://developer.android.com/jetpack/androidx/releases/compose-kotlin
compose-material3 = "1.2.0-alpha12"
coroutines = "1.7.3"
datastore = "1.0.0"
drawerlayout = "1.2.0"
dynamicanimation = "1.0.0"
espresso = "3.5.1"
glance = "1.0.0"
jetbrains-kotlinx-serialization-json = "1.6.2"
junit = "4.13.2"
junit-runner = "1.10.1"
junit5 = "5.10.1"
kotlin = "1.9.21"
kotlinpoet = "1.15.3"
kotlinx-html-jvm = "0.10.1"
kotlinx-serialization-json = "1.6.0"
ksp = "1.9.21-1.0.15"
leakcanary = "2.12"
lifecycle-runtime = "2.6.2"
material = "1.10.0"
mockito-core = "5.8.0"
mockito-kotlin = "5.2.1"
openlocationcode = "1.0.4"
persiancalendar-calculator = "371a91149d1fea9c318ef0def94ca0f93a1be0c2"
persiancalendar-calendar = "a029c1f7fdf7204b8315847b89612eb15a5d519e"
persiancalendar-praytimes = "36eab5bf0b6f5057357d6fbf0007bea3fab73895"
persiancalendar-qr = "60ad1863978b35205549eae6af177c45a1e67307"
recyclerview = "1.3.2"
room = "2.6.1"
sqlite = "2.4.0"
truth = "1.1.5"
viewpager2 = "1.0.0"
work-manager = "2.9.0"

[libraries]
activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidx-activity" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-glance-material3 = { group = "androidx.glance", name = "glance-material3", version.ref = "glance" }
androidx-glance-appwidget = { group = "androidx.glance", name = "glance-appwidget", version.ref = "glance" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
astronomy = { group = "com.github.cosinekitty", name = "astronomy", version.ref = "astronomy" }
browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
compose-accompanist-flowlayout = { group = "com.google.accompanist", name = "accompanist-flowlayout", version.ref = "compose-accompanist" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity" }
compose-animation = { group = "androidx.compose.animation", name = "animation-graphics-android", version.ref = "compose" }
compose-compiler = { group = "androidx.compose.compiler", name = "compiler", version.ref = "compose-compiler" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "compose" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "compose-material3" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "compose" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
drawerlayout = { group = "androidx.drawerlayout", name = "drawerlayout", version.ref = "drawerlayout" }
dynamicanimation = { group = "androidx.dynamicanimation", name = "dynamicanimation", version.ref = "dynamicanimation" }
espresso-contrib = { group = "androidx.test.espresso", name = "espresso-contrib", version.ref = "espresso" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidx-fragment" }
fragment-testing = { group = "androidx.fragment", name = "fragment-testing", version.ref = "androidx-fragment" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit5" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit5" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit5" }
junit-platform-runner = { group = "org.junit.platform", name = "junit-platform-runner", version.ref = "junit-runner" }
kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinpoet" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-html-jvm = { group = "org.jetbrains.kotlinx", name = "kotlinx-html-jvm", version.ref = "kotlinx-html-jvm" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "jetbrains-kotlinx-serialization-json" }
leakcanary = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakcanary" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito-core" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito-kotlin" }
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "androidx-navigation" }
navigation-testing = { group = "androidx.navigation", name = "navigation-testing", version.ref = "androidx-navigation" }
openlocationcode = { group = "com.google.openlocationcode", name = "openlocationcode", version.ref = "openlocationcode" }
persiancalendar-calculator = { group = "com.github.persian-calendar", name = "calculator", version.ref = "persiancalendar-calculator" }
persiancalendar-calendar = { group = "com.github.persian-calendar", name = "calendar", version.ref = "persiancalendar-calendar" }
persiancalendar-praytimes = { group = "com.github.persian-calendar", name = "praytimes", version.ref = "persiancalendar-praytimes" }
persiancalendar-qr = { group = "com.github.persian-calendar", name = "qr", version.ref = "persiancalendar-qr" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
sqlite = { group = "androidx.sqlite", name = "sqlite", version.ref = "sqlite" }
sqlite-framework = { group = "androidx.sqlite", name = "sqlite-framework", version.ref = "sqlite" }
sqlite-ktx = { group = "androidx.sqlite", name = "sqlite-ktx", version.ref = "sqlite" }
test-core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "android-test" }
test-rules = { group = "androidx.test", name = "rules", version.ref = "android-test" }
test-runner = { group = "androidx.test", name = "runner", version.ref = "android-test-runner" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }
work-manager-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work-manager" }

[plugins]
androidx-navigation-safeargs-kotlin = { id = "androidx.navigation.safeargs.kotlin", version.ref = "androidx-navigation" }
com-android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[bundles]
espresso = ["espresso-core", "espresso-contrib"]
mockito = ["mockito-core", "mockito-kotlin"]
room = ["room-ktx", "room-paging", "room-runtime", "sqlite", "sqlite-framework", "sqlite-ktx"]
