[versions]
accompanist = "0.32.0"
agp = "8.1.1"
android-test = "1.5.0"
androidx-activity = "1.7.2"
androidx-fragment = "1.6.1"
androidx-navigation = "2.7.0"
androidx-test-ext-junit = "1.1.5"
appcompat = "1.6.1"
astronomy = "bd2db6a3805ac8a7c559b6b2276e16c1e1793d1f"
browser = "1.6.0"
cardview = "1.0.0"
compose = "1.5.0"
compose-compiler = "1.5.2" # https://developer.android.com/jetpack/androidx/releases/compose-kotlin
core = "1.10.1"
coroutines = "1.7.3"
dynamicanimation = "1.0.0"
espresso = "3.5.1"
junit = "4.13.2"
junit-runner = "1.10.0"
junit5 = "5.10.0"
kotlinpoet = "1.14.2"
kotlinx-html-jvm = "0.9.1"
kotlinx-serialization-json = "1.6.0"
lifecycle-runtime-ktx = "2.6.1"
material = "1.9.0"
material3 = "1.1.1"
mockito-core = "5.5.0"
mockito-kotlin = "5.1.0"
multidex = "2.0.1"
openlocationcode = "1.0.4"
org-jetbrains-kotlin-android = "1.9.0"
persiancalendar-calculator = "371a91149d1fea9c318ef0def94ca0f93a1be0c2"
persiancalendar-calendar = "aa50eff1684cfaceac752c5d812b96e1c0ff95fa"
persiancalendar-praytimes = "36eab5bf0b6f5057357d6fbf0007bea3fab73895"
persiancalendar-qr = "60ad1863978b35205549eae6af177c45a1e67307"
preference = "1.2.1"
recyclerview = "1.3.1"
runner = "1.5.2"
truth = "1.1.5"
viewpager2 = "1.0.0"
work-runtime = "2.8.1"

[libraries]
accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist" }
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
accompanist-themeadapter-material3 = { module = "com.google.accompanist:accompanist-themeadapter-material3", version.ref = "accompanist" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
astronomy = { module = "com.github.cosinekitty:astronomy", version.ref = "astronomy" }
browser = { module = "androidx.browser:browser", version.ref = "browser" }
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core" }
dynamicanimation = { module = "androidx.dynamicanimation:dynamicanimation", version.ref = "dynamicanimation" }
espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espresso" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
fragment-testing = { module = "androidx.fragment:fragment-testing", version.ref = "androidx-fragment" }
junit = { module = "junit:junit", version.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit5" }
junit-platform-runner = { module = "org.junit.platform:junit-platform-runner", version.ref = "junit-runner" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-html-jvm = { module = "org.jetbrains.kotlinx:kotlinx-html-jvm", version.ref = "kotlinx-html-jvm" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
material = { module = "com.google.android.material:material", version.ref = "material" }
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito-core" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }
multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "androidx-navigation" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
openlocationcode = { module = "com.google.openlocationcode:openlocationcode", version.ref = "openlocationcode" }
persiancalendar-calculator = { module = "com.github.persian-calendar:calculator", version.ref = "persiancalendar-calculator" }
persiancalendar-calendar = { module = "com.github.persian-calendar:calendar", version.ref = "persiancalendar-calendar" }
persiancalendar-praytimes = { module = "com.github.persian-calendar:praytimes", version.ref = "persiancalendar-praytimes" }
persiancalendar-qr = { module = "com.github.persian-calendar:qr", version.ref = "persiancalendar-qr" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
rules = { module = "androidx.test:rules", version.ref = "android-test" }
runner = { module = "androidx.test:runner", version.ref = "runner" }
test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "android-test" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work-runtime" }

[plugins]
androidx-navigation-safeargs-kotlin = { id = "androidx.navigation.safeargs.kotlin", version.ref = "androidx-navigation" }
com-android-application = { id = "com.android.application", version.ref = "agp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }

[bundles]
accompanist = ["accompanist-drawablepainter", "accompanist-flowlayout", "accompanist-themeadapter-material3"]
espresso = ["espresso-core", "espresso-contrib"]
mockito = ["mockito-core", "mockito-kotlin"]
